# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-dms
  description: Terraform modules for provisioning and managing AWS DMS resources
  homepage: https://cloudposse.com/accelerate
  topics: data, dms, dynamodb, migration, mysql, oracle, postgres, postgresql, s3, sql, sql-server


